/*
 * pwm_driver.c — Push-Pull PWM Implementation
 *
 * ──────────────────────────────────────────────────────────────────
 * WHY THIS IS FULLY HARDWARE-TIMED (no ISR in the gate-drive path):
 *
 *   The previous revision drove PB7 (Q2) from software, toggled inside
 *   TIM4_IRQHandler on CC3/CC4 compare-match interrupts, while PB6 (Q1)
 *   was a genuine hardware PWM output. That asymmetry raced Q2's
 *   ISR-driven turn-OFF against Q1's hardware-timed turn-ON at the period
 *   wrap, with a margin that SHRUNK as duty rose — as little as 4 µs
 *   (32 CPU cycles at 8 MHz) at PWM_DUTY_MAX_TICKS. Cortex-M3 exception
 *   entry latency plus an unoptimized (-O0) ISR body could exceed that
 *   budget, so PB7 could still be HIGH when PB6 went HIGH again: real
 *   overlap/shoot-through, worst at high duty. That's what showed up on
 *   the scope.
 *
 *   The fix: TIM4 in CENTER-ALIGNED counting mode (CMS bits), with BOTH
 *   Q1 (CH1) and Q2 (CH2, PB7's own native TIM4 channel) as genuine
 *   hardware PWM outputs. No ISR, no software latency, no race — the
 *   compare hardware guarantees the dead-time gap by construction on
 *   every single period, including the very first one after CEN is set.
 *
 * ──────────────────────────────────────────────────────────────────
 * HOW CENTER-ALIGNED MODE PRODUCES TWO NON-OVERLAPPING PULSES:
 *
 *   In center-aligned mode, CNT counts 0 → ARR → 0 → ARR ... (a triangle
 *   wave), one full up+down sweep per switching period. Output-compare
 *   logic is a simple LEVEL comparison (independent of count direction):
 *
 *     PWM Mode 1 (OC1M=110): OCxREF = HIGH while CNT < CCRx.
 *       Over one up+down sweep this is HIGH for a window of width
 *       2×CCRx ticks, CENTERED ON THE TROUGH (CNT=0) — used for Q1.
 *
 *     PWM Mode 2 (OC2M=111): OCxREF = HIGH while CNT >= CCRx.
 *       This is HIGH for a window of width 2×(ARR-CCRx) ticks,
 *       CENTERED ON THE PEAK (CNT=ARR) — used for Q2.
 *
 *   The trough and the peak are exactly half a period apart, so Q1's
 *   pulse (mode 1) and Q2's pulse (mode 2) are naturally centered on
 *   opposite ends of the cycle. Sizing them so ON-time < half-period
 *   guarantees a real, symmetric dead-time gap between them on both
 *   sides, purely from the compare hardware — see pwm_set_duty().
 *
 *   WAVEFORM (at max duty, duty_ticks=128 → half_on=64):
 *
 *     CNT:     0    64        96   160(ARR)  96   64        0
 *     PB6 Q1:  ‾‾‾‾‾|__________________________________|‾‾‾‾‾   (mode 1, CCR1=64)
 *     PB7 Q2:  _____|____|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|____|_____   (mode 2, CCR2=96)
 *                   ^4µs                          ^4µs
 *                  dead   <----------- Q2 ON ----------->  dead
 *
 *   Dead-time gap (each side) = (PWM_HALF_PERIOD_TICKS - duty_ticks)
 *   × 0.125 µs — same formula as the original scheme, just generated by
 *   two independent hardware compare channels instead of one hardware
 *   + one software.
 * ──────────────────────────────────────────────────────────────────
 */

#include "pwm_driver.h"
#include "hw_config.h"
#include "gpio_driver.h"

void pwm_pushpull_init(void)
{
    /* ── 1. Enable TIM4 clock ────────────────────────────────────────
     * TIM4 is on APB1 (address 0x40000800).
     * GPIO and TIM1 are on APB2 — different bus, different enable register. */
    RCC->APB1ENR |= RCC_APB1ENR_TIM4EN;

    /* ── 2. Configure output pins ────────────────────────────────────
     * Both Q1 (PB6, TIM4 CH1) and Q2 (PB7, TIM4 CH2) are now hardware
     * PWM outputs — alternate-function push-pull. No plain-GPIO pin,
     * no software toggling, no gpio_write() in the gate-drive path. */
    gpio_af_output_init(PWM_PORT, PWM_PIN_Q1);
    gpio_af_output_init(PWM_PORT, PWM_PIN_Q2);

    /* ── 3. Timebase ─────────────────────────────────────────────────
     * PSC = 0 → tick = 1 / 8 MHz = 0.125 µs.
     * Center-aligned mode counts a full 0→ARR→0 sweep per period, so
     * ARR is now the HALF-period tick count (160 = 20 µs), giving a
     * full period of 2×160 ticks = 320 ticks = 40 µs = 25 kHz — the
     * same switching frequency as before. */
    TIM4->PSC = PWM_PSC;
    TIM4->ARR = PWM_HALF_PERIOD_TICKS;

    /* ── 4. CH1: Hardware PWM Mode 1 for Q1 (PB6) ────────────────────
     * OC1M = 0b110 (PWM Mode 1): OC1REF = HIGH while CNT < CCR1.
     * In center-aligned mode this produces a pulse of width 2×CCR1,
     * centered on the trough (CNT=0 / period boundary). */
    TIM4->CCR1   = PWM_DUTY_MIN_TICKS / 2u;   /* Safe startup duty (half-width) */
    TIM4->CCMR1 &= ~TIM_CCMR1_OC1M;
    TIM4->CCMR1 |=  (0x6u << 4u);              /* PWM Mode 1 = 0b110             */
    TIM4->CCMR1 |=  TIM_CCMR1_OC1PE;           /* CCR1 preload enable            */
    TIM4->CCER  |=  TIM_CCER_CC1E;             /* Connect CH1 to PB6 pin         */

    /* ── 5. CH2: Hardware PWM Mode 2 for Q2 (PB7) ────────────────────
     * OC2M = 0b111 (PWM Mode 2, inverted sense): OC2REF = HIGH while
     * CNT >= CCR2. In center-aligned mode this produces a pulse of
     * width 2×(ARR-CCR2), centered on the peak (CNT=ARR) — exactly
     * half a period away from Q1's pulse. This is what replaces the
     * old CC3/CC4 software toggle: PB7 is now driven purely by the
     * timer's compare hardware, same as PB6. */
    TIM4->CCR2   = PWM_HALF_PERIOD_TICKS - (PWM_DUTY_MIN_TICKS / 2u); /* Startup */
    TIM4->CCMR1 &= ~TIM_CCMR1_OC2M;
    TIM4->CCMR1 |=  (0x7u << 12u);             /* PWM Mode 2 = 0b111             */
    TIM4->CCMR1 |=  TIM_CCMR1_OC2PE;           /* CCR2 preload enable            */
    TIM4->CCER  |=  TIM_CCER_CC2E;             /* Connect CH2 to PB7 pin         */

    /* ── 6. Center-aligned counting mode ─────────────────────────────
     * CMS = 01 (Center-aligned mode 1): CNT counts up 0→ARR, then down
     * ARR→0, repeating. This is what makes the OC1M/OC2M compare logic
     * above produce symmetric, oppositely-centered pulses. (CMS mode
     * 1 vs 2 vs 3 only changes WHEN the compare-match interrupt FLAG
     * is set, not the OCxREF output logic — irrelevant here since no
     * ISR is used for gate driving, so mode 1 is chosen arbitrarily.) */
    TIM4->CR1 &= ~TIM_CR1_CMS;
    TIM4->CR1 |=  TIM_CR1_CMS_0;               /* CMS = 01                       */

    /* ── 7. Reset counter and start ──────────────────────────────────
     * CNT = 0 (the trough) ensures the first sweep starts at a known,
     * correct phase — with CCR1/CCR2/ARR already loaded with their real
     * values above (written before their respective *PE bits were set,
     * so those writes landed directly in the active register, not just
     * the preload shadow) there is no startup glitch on the first period.
     *
     * ARPE: ARR preload, same buffering reasoning as OC1PE/OC2PE.
     * CEN:  counter enable — PWM starts here. */
    TIM4->CNT   = 0u;
    TIM4->CR1  |= TIM_CR1_ARPE;
    TIM4->CR1  |= TIM_CR1_CEN;
}

void pwm_set_duty(uint16_t duty_ticks)
{
    /* Enforce safe range.
     * MIN = 16: guarantees minimum dead-time on each gap.
     * MAX = 128: enforces 16 µs maximum ON-time (Rev E specification),
     *   staying well below PWM_HALF_PERIOD_TICKS (160) so a real dead-time
     *   gap always remains — see hw_config.h invariants. */
    if (duty_ticks < PWM_DUTY_MIN_TICKS) { duty_ticks = PWM_DUTY_MIN_TICKS; }
    if (duty_ticks > PWM_DUTY_MAX_TICKS) { duty_ticks = PWM_DUTY_MAX_TICKS; }

    /* half_on = ticks from the pulse center to each edge. Deriving both
     * CCR1 and CCR2 from the SAME half_on value is what keeps Q1 and
     * Q2 at identical ON-time (volt-second balance) at every duty. */
    uint16_t half_on = duty_ticks / 2u;

    /* Q1 pulse (mode 1, centered on trough): width = 2×CCR1 = duty_ticks.
     * CCR1/CCR2 preload active → both take effect together at the next
     * period boundary (CNT=0), never mid-sweep. */
    TIM4->CCR1 = half_on;

    /* Q2 pulse (mode 2, centered on peak): width = 2×(ARR-CCR2) = duty_ticks. */
    TIM4->CCR2 = PWM_HALF_PERIOD_TICKS - half_on;
}
